### ISSUE TITLE
[7.19] AntiVirus: Service auto-discovery

### ISSUE THREAD

**Issue by tminich** [aedart/athenaeum#177]
## Description

Most Laravel packages have auto-discovery for their services. Is there a reason why the service for the AntiVirus package needs to be added manually?

## Possible solution

Add a `extra->laravel->providers` entry to composer.json to allow the service to be auto-discovered.

**Comment by aedart** [comment]
Hi @tminich. Thus far I have avoided using auto-discovery, because some of my packages offer more than one service provider and I wanted to avoid creating conflicts / unwanted situations by automatically registration of certain bindings. This is especially true when I overwrite some of Laravel's own native bindings (_but that is not the case for the AntiVirus package_).
Should you require the AntiVirus components for more than one project, then you can always create a "wrapper" package that automatically discovers it - or perhaps your own custom service provider with configuration and settings that fit your purposes.

In future major version(s), I might reconsider my approach for all of my packages. But for now, you will have to manually register the required service provider (_sorry_).

**Comment by tminich** [comment]
That's perfectly reasonable. Basically I was wondering if it's intentional or an oversight and you cleared that up =)

Feel free to just close this or leave it open if you want to keep it as a reminder for the future.
