### ISSUE TITLE
Antivirus stream close method not compatible

### ISSUE THREAD

**Issue by NotMings** [aedart/athenaeum#187]
## Description

Error using empty scanner when using antivirus program

`local.ERROR: Declaration of Aedart\Streams\Stream::close() must be compatible with Psr\Http\Message\StreamInterface::close(): void {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Aedart\\Streams\\Stream::close() must be compatible with Psr\\Http\\Message\\StreamInterface::close(): void at /var/www/html/vendor/aedart/athenaeum-streams/src/Stream.php:123)`

## Version & Environment

- athenaeum: 8.0
- php: 8.2
- laravel: 11

## Steps to reproduce

_How can the defect be reproduced? E.g._

1. install athenaeum-antivirus
2. set config `default_scanner` to none (cannot use null, which involves forced conversion, which is also a bug)
![image](https://github.com/aedart/athenaeum/assets/57120572/f1ba0673-14d5-44ba-a571-90b48721ea52)
3. use validation rule

## Possible solution

The declaration of the Aedart\Streams\Stream::close() method needs to be modified to include: void return type declaration

**Comment by NotMings** [comment]
In addition to the close method, the seek and rewind methods do not indicate return values. 
![image](https://github.com/aedart/athenaeum/assets/57120572/cad69820-cd63-4695-8206-e0ab23549c5c)
![image](https://github.com/aedart/athenaeum/assets/57120572/59b9c01d-cb27-4649-a9ec-7a9817b58451)

**Comment by aedart** [comment]
Hi @NotMings 
Thank you for noticing this defect. This was sadly caused by a "bad" dependency. I have now released a new minor version, which replaced the `psr/http-message: ^1.1 || ^2.0` dependency with `psr/http-message: ^1.1`.

The return types are only available from version 2.x, of the Psr package. However, I cannot switch to version 2.0 yet, because it will introduce a breaking change in the current Athenaeum version 8-series. This can at the earliest be done next year, in the upcoming version 9-series (_see #188_). I'm really sorry about this defect, it was very careless of me. Hopefully you can use the Antivirus package as intended, with the minor version I have released.
