### ISSUE TITLE
[athenaeum-flysystem-db] Unable to persist binary data to MariaDB

### ISSUE THREAD

**Issue by goldmont** [aedart/athenaeum#189]
## Description

Hi,

After a few days I'm still unable to persist my binary data into a MariaDB instance using Laravel. I tried the example in the [documentation](https://aedart.github.io/athenaeum/archive/current/flysystem/db/setup.html#use-storage-disk) page and the library seems to save everything correctly into the database except to the blob field which contains always something like `Resource id #...`. Whatever kind of data I try to save, the result is the same. Could you help me please?

## Version & Environment

Laravel: 9
athenaeum-flysystem-db: 6.8.1

## Steps to reproduce

1. `Storage::disk('my_disk')->put('example.txt', 'Contents');`

![image](https://github.com/aedart/athenaeum/assets/6855692/abeb79ce-f41d-4560-a765-997eb329bf14)

![image](https://github.com/aedart/athenaeum/assets/6855692/59fb56fe-17f5-4101-95c3-f0386200cd51)

![image](https://github.com/aedart/athenaeum/assets/6855692/a0db5e5a-cf57-4280-a985-37c59dcf92d1)

![image](https://github.com/aedart/athenaeum/assets/6855692/368e88c4-03dd-4183-ad44-42d7c3436c87)

## Expected behaviour

To see the correct data (the text "Contents" in my case)

**Comment by goldmont** [comment]
Apparently the problem is this [line](https://github.com/aedart/athenaeum-flysystem-db/blob/6.8.1/src/Adapters/DatabaseAdapter.php#L964). The latest version of this library (8.3.0) should be affected by this too.

The comment reads:

> Database driver should automatically deal with "resource". Alternatively, the resource should be converted to a string, but that COULD increase memory consumption a lot (depending on filesize).

Since the value of the key `contents` is a resource, then transforming to string the resource results in the error I described above. Instead of calling the `resource()` method, I'm currently using `getContents()` and it works like a charm with any kind of data I tested. What are your considerations?

```php
    protected function prepareContentsRecord(string $path, FileStream $stream, Config $config): array
    {
        // Note: path is not used here, but it is kept to allow eventual customisation / extended
        // versions of this adapter!


        return [
            'hash' => $this->resolveContentHash($stream, $config),


            // Initial reference count. This is ONLY valid when inserting a new
            // record. It must be updated when existing record is updated.
            'reference_count' => 1,


            // Database driver should automatically deal with "resource".
            // Alternatively, the resource should be converted to a string, but
            // that COULD increase memory consumption a lot (depending on filesize).
            'contents' => $stream
                ->positionToStart()
                ->resource()
        ];
    }
```

**Comment by aedart** [comment]
Hi @goldmont 

Thx for reporting this issue. I will try to take a look it as soon as possible,... but this could be a while - got lots of stuff to do this weekend (_really sorry_). If your work-around / hotfix works for you right now, keep it (_You can eventually create a custom extended version of this `DatabaseAdapter`, and register it in the same way as in the [Service Provider](https://github.com/aedart/athenaeum-flysystem-db/blob/6.8.1/src/Providers/FlysystemDatabaseAdapterServiceProvider.php#L44)_). 
Hopefully I can take some time for this, early next week (_no promises_).

In the mean time, my best guess is that either Laravel's database component or PDO is no able to handle a resource (_for Maria DB_), in the same way that other drivers do (_see old issue / pull request for details_):
* https://github.com/laravel/framework/issues/41180
* https://github.com/laravel/framework/pull/41233
But to verify this, I will have to get MariaDB running and test this myself.

Also, you are using an outdated / unsupported version of Laravel & this package. Even when/if I can reproduce this issue, I cannot guarantee to release a patch for the version `6.x` series of this package. If there is any chance that you can upgrade your application, then I recommend it (_just in case that this issue is related to PHP's PDO_).

**Comment by goldmont** [comment]
Hi,

This is exactly what I did. I've extended both the adapter and the provider.

FYI:
However, on MySQL the problem doesn't occur. So there might be some difference on how the driver handles PHP resources on the basis of the database (MySQL or MariaDB).

**Comment by aedart** [comment]
I fear that this could be more PDO related. If so, then it will become very difficult to resolve. In any case, I will try to reproduce this defect in my current setup (_latest version of Laravel, Athenaeum, PHP v8.2,...etc_).

**Comment by aedart** [comment]
Hi @goldmont 

I have attempted to reproduce this issue, but sadly without any success. Please see pull request #190 for a few details.
There were two minor bugs, which affected postgresql and mariadb database drivers. Yet, none of them were of this nature.
Note that the tests that I have conducted includes [League's own Flysystem Adapter Test Utilities](https://github.com/thephpleague/flysystem-adapter-test-utilities).

As I previously mentioned, it can either be your PHP / PDO and or your version of Laravel that are outdated and thus causing this behaviour. If you are able to update your application's dependencies, then you should do so. Otherwise, your own work-around could be the way forward, until you do have the time/resources for upgrading your dependencies and system.

I'm sorry for not being able to help you more than this. Please do feel free to open another issue, if this should arise again - _using a newer version of this package, etc._

**Comment by aedart** [comment]
Hi @goldmont 

From what you have written, I can see that your Laravel version (_9.54.16_) does NOT support resources as binding values for queries. This might explain your problem. Try to upgrade to [`9.3.0`](https://github.com/laravel/framework/blob/9.x/CHANGELOG.md#v930-2022-03-02) - this should not be a breaking change for you (_I hope_).

As for the remaining of your questions:
- MySQL: N/A (_I only installed MariaDB_)
- MariaDB: 15.1, Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64)
- PHP: 8.2.19
- Laravel: 11.8
- League/flysystem: 3.28

**Comment by aedart** [comment]
@goldmont Could you please let me know, if I _should_ close this issue - or keep it open?

**Comment by goldmont** [comment]
Hi,

You can close this issue for now. Once upgraded to L11, I'll let you know here 👍🏻 Thank you
